// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: uggly.proto

package uggly

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PixelSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pixels []*Pixel `protobuf:"bytes,10,rep,name=pixels,proto3" json:"pixels,omitempty"`
}

func (x *PixelSlice) Reset() {
	*x = PixelSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PixelSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelSlice) ProtoMessage() {}

func (x *PixelSlice) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelSlice.ProtoReflect.Descriptor instead.
func (*PixelSlice) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{0}
}

func (x *PixelSlice) GetPixels() []*Pixel {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type Pixel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C        int32  `protobuf:"varint,10,opt,name=c,proto3" json:"c,omitempty"`
	St       *Style `protobuf:"bytes,11,opt,name=st,proto3" json:"st,omitempty"`
	IsBorder bool   `protobuf:"varint,12,opt,name=isBorder,proto3" json:"isBorder,omitempty"`
}

func (x *Pixel) Reset() {
	*x = Pixel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pixel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pixel) ProtoMessage() {}

func (x *Pixel) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pixel.ProtoReflect.Descriptor instead.
func (*Pixel) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{1}
}

func (x *Pixel) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Pixel) GetSt() *Style {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *Pixel) GetIsBorder() bool {
	if x != nil {
		return x.IsBorder
	}
	return false
}

// DivBox is a core element of the protocol. No content can exist
//outside of a DivBox. It requires that some basic properties are included
//such as fill and border geometry but the rawContents property is open
//to fill with whatever content is desired.
type DivBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Border      bool          `protobuf:"varint,10,opt,name=border,proto3" json:"border,omitempty"`
	BorderW     int32         `protobuf:"varint,11,opt,name=borderW,proto3" json:"borderW,omitempty"`
	BorderChar  int32         `protobuf:"varint,12,opt,name=borderChar,proto3" json:"borderChar,omitempty"`
	FillChar    int32         `protobuf:"varint,14,opt,name=fillChar,proto3" json:"fillChar,omitempty"`
	StartX      int32         `protobuf:"varint,15,opt,name=startX,proto3" json:"startX,omitempty"`
	StartY      int32         `protobuf:"varint,16,opt,name=startY,proto3" json:"startY,omitempty"`
	Width       int32         `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	Height      int32         `protobuf:"varint,18,opt,name=Height,proto3" json:"Height,omitempty"`
	RawContents []*PixelSlice `protobuf:"bytes,19,rep,name=rawContents,proto3" json:"rawContents,omitempty"`
	BorderSt    *Style        `protobuf:"bytes,20,opt,name=borderSt,proto3" json:"borderSt,omitempty"`
	FillSt      *Style        `protobuf:"bytes,21,opt,name=fillSt,proto3" json:"fillSt,omitempty"`
}

func (x *DivBox) Reset() {
	*x = DivBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivBox) ProtoMessage() {}

func (x *DivBox) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivBox.ProtoReflect.Descriptor instead.
func (*DivBox) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{2}
}

func (x *DivBox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DivBox) GetBorder() bool {
	if x != nil {
		return x.Border
	}
	return false
}

func (x *DivBox) GetBorderW() int32 {
	if x != nil {
		return x.BorderW
	}
	return 0
}

func (x *DivBox) GetBorderChar() int32 {
	if x != nil {
		return x.BorderChar
	}
	return 0
}

func (x *DivBox) GetFillChar() int32 {
	if x != nil {
		return x.FillChar
	}
	return 0
}

func (x *DivBox) GetStartX() int32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *DivBox) GetStartY() int32 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *DivBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DivBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DivBox) GetRawContents() []*PixelSlice {
	if x != nil {
		return x.RawContents
	}
	return nil
}

func (x *DivBox) GetBorderSt() *Style {
	if x != nil {
		return x.BorderSt
	}
	return nil
}

func (x *DivBox) GetFillSt() *Style {
	if x != nil {
		return x.FillSt
	}
	return nil
}

// TextBlob is a special kind of element that natively understands
//text blocks intended for human readability. Obviously it has a content
//property but also understands things like text style and text wrap when
//the text is larger than the width of the container it was assigned to.
//
//A TextBlob can be assigned to multiple Divs in case you wanted to re-use
//text in multiple places for some reason.
type TextBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content  string   `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Wrap     bool     `protobuf:"varint,11,opt,name=wrap,proto3" json:"wrap,omitempty"`
	Style    *Style   `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	DivNames []string `protobuf:"bytes,15,rep,name=divNames,proto3" json:"divNames,omitempty"`
}

func (x *TextBlob) Reset() {
	*x = TextBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlob) ProtoMessage() {}

func (x *TextBlob) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlob.ProtoReflect.Descriptor instead.
func (*TextBlob) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{3}
}

func (x *TextBlob) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextBlob) GetWrap() bool {
	if x != nil {
		return x.Wrap
	}
	return false
}

func (x *TextBlob) GetStyle() *Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *TextBlob) GetDivNames() []string {
	if x != nil {
		return x.DivNames
	}
	return nil
}

// DivBoxes is an array of DivBox
type DivBoxes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxes []*DivBox `protobuf:"bytes,10,rep,name=boxes,proto3" json:"boxes,omitempty"`
}

func (x *DivBoxes) Reset() {
	*x = DivBoxes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivBoxes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivBoxes) ProtoMessage() {}

func (x *DivBoxes) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivBoxes.ProtoReflect.Descriptor instead.
func (*DivBoxes) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{4}
}

func (x *DivBoxes) GetBoxes() []*DivBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

// Style is a base property used in divBox fill, border fill, and textboxes
//with fg being foreground color, bg being background color, and attr
//being text attributes like strikethrough and underline.
//
//It's essentially a passthrough of the capabilities of tcell's style
//https://github.com/gdamore/tcell/blob/master/style.go
type Style struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fg   string `protobuf:"bytes,10,opt,name=fg,proto3" json:"fg,omitempty"`
	Bg   string `protobuf:"bytes,11,opt,name=bg,proto3" json:"bg,omitempty"`
	Attr string `protobuf:"bytes,12,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *Style) Reset() {
	*x = Style{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Style) ProtoMessage() {}

func (x *Style) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Style.ProtoReflect.Descriptor instead.
func (*Style) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{5}
}

func (x *Style) GetFg() string {
	if x != nil {
		return x.Fg
	}
	return ""
}

func (x *Style) GetBg() string {
	if x != nil {
		return x.Bg
	}
	return ""
}

func (x *Style) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyStroke string `protobuf:"bytes,10,opt,name=keyStroke,proto3" json:"keyStroke,omitempty"`
	PageName  string `protobuf:"bytes,11,opt,name=pageName,proto3" json:"pageName,omitempty"`
	Server    string `protobuf:"bytes,12,opt,name=server,proto3" json:"server,omitempty"`
	Port      string `protobuf:"bytes,13,opt,name=port,proto3" json:"port,omitempty"`
	FormName  string `protobuf:"bytes,14,opt,name=formName,proto3" json:"formName,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{6}
}

func (x *Link) GetKeyStroke() string {
	if x != nil {
		return x.KeyStroke
	}
	return ""
}

func (x *Link) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *Link) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Link) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Link) GetFormName() string {
	if x != nil {
		return x.FormName
	}
	return ""
}

type TextBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	TabOrder         int32  `protobuf:"varint,11,opt,name=tabOrder,proto3" json:"tabOrder,omitempty"`
	DefaultValue     string `protobuf:"bytes,12,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Description      string `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	PositionX        int32  `protobuf:"varint,14,opt,name=positionX,proto3" json:"positionX,omitempty"` // relative within DivBox
	PositionY        int32  `protobuf:"varint,15,opt,name=positionY,proto3" json:"positionY,omitempty"` // relative within DivBox
	Height           int32  `protobuf:"varint,16,opt,name=height,proto3" json:"height,omitempty"`
	Width            int32  `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	StyleCursor      *Style `protobuf:"bytes,18,opt,name=styleCursor,proto3" json:"styleCursor,omitempty"`
	StyleFill        *Style `protobuf:"bytes,19,opt,name=styleFill,proto3" json:"styleFill,omitempty"`
	StyleText        *Style `protobuf:"bytes,20,opt,name=styleText,proto3" json:"styleText,omitempty"`
	StyleDescription *Style `protobuf:"bytes,21,opt,name=styleDescription,proto3" json:"styleDescription,omitempty"`
	ShowDescription  bool   `protobuf:"varint,22,opt,name=showDescription,proto3" json:"showDescription,omitempty"`
}

func (x *TextBox) Reset() {
	*x = TextBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBox) ProtoMessage() {}

func (x *TextBox) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBox.ProtoReflect.Descriptor instead.
func (*TextBox) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{7}
}

func (x *TextBox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextBox) GetTabOrder() int32 {
	if x != nil {
		return x.TabOrder
	}
	return 0
}

func (x *TextBox) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *TextBox) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TextBox) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *TextBox) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *TextBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TextBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TextBox) GetStyleCursor() *Style {
	if x != nil {
		return x.StyleCursor
	}
	return nil
}

func (x *TextBox) GetStyleFill() *Style {
	if x != nil {
		return x.StyleFill
	}
	return nil
}

func (x *TextBox) GetStyleText() *Style {
	if x != nil {
		return x.StyleText
	}
	return nil
}

func (x *TextBox) GetStyleDescription() *Style {
	if x != nil {
		return x.StyleDescription
	}
	return nil
}

func (x *TextBox) GetShowDescription() bool {
	if x != nil {
		return x.ShowDescription
	}
	return false
}

type Form struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string     `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	DivName    string     `protobuf:"bytes,11,opt,name=divName,proto3" json:"divName,omitempty"`
	TextBoxes  []*TextBox `protobuf:"bytes,12,rep,name=textBoxes,proto3" json:"textBoxes,omitempty"`
	SubmitLink *Link      `protobuf:"bytes,13,opt,name=submitLink,proto3" json:"submitLink,omitempty"`
}

func (x *Form) Reset() {
	*x = Form{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Form) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Form) ProtoMessage() {}

func (x *Form) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Form.ProtoReflect.Descriptor instead.
func (*Form) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{8}
}

func (x *Form) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Form) GetDivName() string {
	if x != nil {
		return x.DivName
	}
	return ""
}

func (x *Form) GetTextBoxes() []*TextBox {
	if x != nil {
		return x.TextBoxes
	}
	return nil
}

func (x *Form) GetSubmitLink() *Link {
	if x != nil {
		return x.SubmitLink
	}
	return nil
}

type FormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string         `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	TextBoxData []*TextBoxData `protobuf:"bytes,11,rep,name=textBoxData,proto3" json:"textBoxData,omitempty"`
}

func (x *FormData) Reset() {
	*x = FormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormData) ProtoMessage() {}

func (x *FormData) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormData.ProtoReflect.Descriptor instead.
func (*FormData) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{9}
}

func (x *FormData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FormData) GetTextBoxData() []*TextBoxData {
	if x != nil {
		return x.TextBoxData
	}
	return nil
}

type TextBoxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Contents string `protobuf:"bytes,11,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *TextBoxData) Reset() {
	*x = TextBoxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextBoxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBoxData) ProtoMessage() {}

func (x *TextBoxData) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBoxData.ProtoReflect.Descriptor instead.
func (*TextBoxData) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{10}
}

func (x *TextBoxData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextBoxData) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

type Elements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextBlobs []*TextBlob `protobuf:"bytes,10,rep,name=textBlobs,proto3" json:"textBlobs,omitempty"`
	Forms     []*Form     `protobuf:"bytes,11,rep,name=forms,proto3" json:"forms,omitempty"`
}

func (x *Elements) Reset() {
	*x = Elements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Elements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elements) ProtoMessage() {}

func (x *Elements) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elements.ProtoReflect.Descriptor instead.
func (*Elements) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{11}
}

func (x *Elements) GetTextBlobs() []*TextBlob {
	if x != nil {
		return x.TextBlobs
	}
	return nil
}

func (x *Elements) GetForms() []*Form {
	if x != nil {
		return x.Forms
	}
	return nil
}

type PageListing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PageListing) Reset() {
	*x = PageListing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageListing) ProtoMessage() {}

func (x *PageListing) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageListing.ProtoReflect.Descriptor instead.
func (*PageListing) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{12}
}

func (x *PageListing) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DivBoxes *DivBoxes `protobuf:"bytes,10,opt,name=divBoxes,proto3" json:"divBoxes,omitempty"`
	Elements *Elements `protobuf:"bytes,11,opt,name=elements,proto3" json:"elements,omitempty"`
	Name     string    `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Links    []*Link   `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{13}
}

func (x *PageResponse) GetDivBoxes() *DivBoxes {
	if x != nil {
		return x.DivBoxes
	}
	return nil
}

func (x *PageResponse) GetElements() *Elements {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *PageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type PageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string      `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	ClientWidth  int32       `protobuf:"varint,11,opt,name=clientWidth,proto3" json:"clientWidth,omitempty"`
	ClientHeight int32       `protobuf:"varint,12,opt,name=clientHeight,proto3" json:"clientHeight,omitempty"`
	FormData     []*FormData `protobuf:"bytes,13,rep,name=formData,proto3" json:"formData,omitempty"`
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{14}
}

func (x *PageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageRequest) GetClientWidth() int32 {
	if x != nil {
		return x.ClientWidth
	}
	return 0
}

func (x *PageRequest) GetClientHeight() int32 {
	if x != nil {
		return x.ClientHeight
	}
	return 0
}

func (x *PageRequest) GetFormData() []*FormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

type FeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages []*PageListing `protobuf:"bytes,10,rep,name=pages,proto3" json:"pages,omitempty"`
	Notes string         `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{15}
}

func (x *FeedResponse) GetPages() []*PageListing {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *FeedResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type FeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendData bool `protobuf:"varint,10,opt,name=sendData,proto3" json:"sendData,omitempty"`
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{16}
}

func (x *FeedRequest) GetSendData() bool {
	if x != nil {
		return x.SendData
	}
	return false
}

var File_uggly_proto protoreflect.FileDescriptor

var file_uggly_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75,
	0x67, 0x67, 0x6c, 0x79, 0x22, 0x32, 0x0a, 0x0a, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x69, 0x78, 0x65, 0x6c,
	0x52, 0x06, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x73, 0x22, 0x4f, 0x0a, 0x05, 0x50, 0x69, 0x78, 0x65,
	0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x63, 0x12,
	0x1c, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x02, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xed, 0x02, 0x0a, 0x06, 0x44, 0x69,
	0x76, 0x42, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x57, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x57, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x6c, 0x43, 0x68, 0x61, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x6c, 0x43, 0x68, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x59, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x59, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x33, 0x0a, 0x0b, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x13, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x67, 0x67, 0x6c,
	0x79, 0x2e, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x72, 0x61,
	0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x18, 0x15, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c,
	0x65, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x22, 0x78, 0x0a, 0x08, 0x54, 0x65, 0x78,
	0x74, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x72, 0x61, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x77,
	0x72, 0x61, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x76, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x76, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x08, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x52, 0x05, 0x62,
	0x6f, 0x78, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x05, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x66, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x66, 0x67, 0x12, 0x0e, 0x0a,
	0x02, 0x62, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x62, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74,
	0x72, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65,
	0x79, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b,
	0x65, 0x79, 0x53, 0x74, 0x72, 0x6f, 0x6b, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd5, 0x03, 0x0a,
	0x07, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x61, 0x62, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x74, 0x61, 0x62, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x11, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x0b, 0x73, 0x74, 0x79, 0x6c,
	0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x74, 0x79, 0x6c,
	0x65, 0x46, 0x69, 0x6c, 0x6c, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x74, 0x79, 0x6c, 0x65,
	0x46, 0x69, 0x6c, 0x6c, 0x12, 0x2a, 0x0a, 0x09, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x54, 0x65, 0x78,
	0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e,
	0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x38, 0x0a, 0x10, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67,
	0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x10, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x68,
	0x6f, 0x77, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x16, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0f, 0x73, 0x68, 0x6f, 0x77, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x04, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x74,
	0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x52, 0x09,
	0x74, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x54, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x42, 0x6f,
	0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0b, 0x74, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x0b,
	0x54, 0x65, 0x78, 0x74, 0x42, 0x6f, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x08, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x6c, 0x6f, 0x62, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x67, 0x67,
	0x6c, 0x79, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x09, 0x74, 0x65, 0x78,
	0x74, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x61, 0x67,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9f, 0x01, 0x0a,
	0x0c, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x08, 0x64, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73,
	0x52, 0x08, 0x64, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75,
	0x67, 0x67, 0x6c, 0x79, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75, 0x67, 0x67,
	0x6c, 0x79, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x94,
	0x01, 0x0a, 0x0b, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x64, 0x74,
	0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x67, 0x67,
	0x6c, 0x79, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x72,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x0c, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x32, 0x3c, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x64, 0x12, 0x12, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x46, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x3c,
	0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6e, 0x64, 0x69,
	0x63, 0x6f, 0x74, 0x74, 0x2f, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_uggly_proto_rawDescOnce sync.Once
	file_uggly_proto_rawDescData = file_uggly_proto_rawDesc
)

func file_uggly_proto_rawDescGZIP() []byte {
	file_uggly_proto_rawDescOnce.Do(func() {
		file_uggly_proto_rawDescData = protoimpl.X.CompressGZIP(file_uggly_proto_rawDescData)
	})
	return file_uggly_proto_rawDescData
}

var file_uggly_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_uggly_proto_goTypes = []interface{}{
	(*PixelSlice)(nil),   // 0: uggly.PixelSlice
	(*Pixel)(nil),        // 1: uggly.Pixel
	(*DivBox)(nil),       // 2: uggly.DivBox
	(*TextBlob)(nil),     // 3: uggly.TextBlob
	(*DivBoxes)(nil),     // 4: uggly.DivBoxes
	(*Style)(nil),        // 5: uggly.Style
	(*Link)(nil),         // 6: uggly.Link
	(*TextBox)(nil),      // 7: uggly.TextBox
	(*Form)(nil),         // 8: uggly.Form
	(*FormData)(nil),     // 9: uggly.FormData
	(*TextBoxData)(nil),  // 10: uggly.TextBoxData
	(*Elements)(nil),     // 11: uggly.Elements
	(*PageListing)(nil),  // 12: uggly.PageListing
	(*PageResponse)(nil), // 13: uggly.PageResponse
	(*PageRequest)(nil),  // 14: uggly.PageRequest
	(*FeedResponse)(nil), // 15: uggly.FeedResponse
	(*FeedRequest)(nil),  // 16: uggly.FeedRequest
}
var file_uggly_proto_depIdxs = []int32{
	1,  // 0: uggly.PixelSlice.pixels:type_name -> uggly.Pixel
	5,  // 1: uggly.Pixel.st:type_name -> uggly.Style
	0,  // 2: uggly.DivBox.rawContents:type_name -> uggly.PixelSlice
	5,  // 3: uggly.DivBox.borderSt:type_name -> uggly.Style
	5,  // 4: uggly.DivBox.fillSt:type_name -> uggly.Style
	5,  // 5: uggly.TextBlob.style:type_name -> uggly.Style
	2,  // 6: uggly.DivBoxes.boxes:type_name -> uggly.DivBox
	5,  // 7: uggly.TextBox.styleCursor:type_name -> uggly.Style
	5,  // 8: uggly.TextBox.styleFill:type_name -> uggly.Style
	5,  // 9: uggly.TextBox.styleText:type_name -> uggly.Style
	5,  // 10: uggly.TextBox.styleDescription:type_name -> uggly.Style
	7,  // 11: uggly.Form.textBoxes:type_name -> uggly.TextBox
	6,  // 12: uggly.Form.submitLink:type_name -> uggly.Link
	10, // 13: uggly.FormData.textBoxData:type_name -> uggly.TextBoxData
	3,  // 14: uggly.Elements.textBlobs:type_name -> uggly.TextBlob
	8,  // 15: uggly.Elements.forms:type_name -> uggly.Form
	4,  // 16: uggly.PageResponse.divBoxes:type_name -> uggly.DivBoxes
	11, // 17: uggly.PageResponse.elements:type_name -> uggly.Elements
	6,  // 18: uggly.PageResponse.links:type_name -> uggly.Link
	9,  // 19: uggly.PageRequest.formData:type_name -> uggly.FormData
	12, // 20: uggly.FeedResponse.pages:type_name -> uggly.PageListing
	16, // 21: uggly.Feed.GetFeed:input_type -> uggly.FeedRequest
	14, // 22: uggly.Page.GetPage:input_type -> uggly.PageRequest
	15, // 23: uggly.Feed.GetFeed:output_type -> uggly.FeedResponse
	13, // 24: uggly.Page.GetPage:output_type -> uggly.PageResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_uggly_proto_init() }
func file_uggly_proto_init() {
	if File_uggly_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uggly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PixelSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pixel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivBoxes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Style); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Form); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextBoxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Elements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageListing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uggly_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_uggly_proto_goTypes,
		DependencyIndexes: file_uggly_proto_depIdxs,
		MessageInfos:      file_uggly_proto_msgTypes,
	}.Build()
	File_uggly_proto = out.File
	file_uggly_proto_rawDesc = nil
	file_uggly_proto_goTypes = nil
	file_uggly_proto_depIdxs = nil
}
