// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: uggly.proto

package uggly

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendData bool `protobuf:"varint,10,opt,name=sendData,proto3" json:"sendData,omitempty"`
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{0}
}

func (x *FeedRequest) GetSendData() bool {
	if x != nil {
		return x.SendData
	}
	return false
}

type PixelSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pixels []*Pixel `protobuf:"bytes,10,rep,name=pixels,proto3" json:"pixels,omitempty"`
}

func (x *PixelSlice) Reset() {
	*x = PixelSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PixelSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelSlice) ProtoMessage() {}

func (x *PixelSlice) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelSlice.ProtoReflect.Descriptor instead.
func (*PixelSlice) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{1}
}

func (x *PixelSlice) GetPixels() []*Pixel {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type Pixel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C        int32  `protobuf:"varint,10,opt,name=c,proto3" json:"c,omitempty"`
	St       *Style `protobuf:"bytes,11,opt,name=st,proto3" json:"st,omitempty"`
	IsBorder bool   `protobuf:"varint,12,opt,name=isBorder,proto3" json:"isBorder,omitempty"`
}

func (x *Pixel) Reset() {
	*x = Pixel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pixel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pixel) ProtoMessage() {}

func (x *Pixel) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pixel.ProtoReflect.Descriptor instead.
func (*Pixel) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{2}
}

func (x *Pixel) GetC() int32 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *Pixel) GetSt() *Style {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *Pixel) GetIsBorder() bool {
	if x != nil {
		return x.IsBorder
	}
	return false
}

type DivBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Border      bool          `protobuf:"varint,10,opt,name=border,proto3" json:"border,omitempty"`
	BorderW     int32         `protobuf:"varint,11,opt,name=borderW,proto3" json:"borderW,omitempty"`
	BorderChar  int32         `protobuf:"varint,12,opt,name=borderChar,proto3" json:"borderChar,omitempty"`
	FillChar    int32         `protobuf:"varint,14,opt,name=fillChar,proto3" json:"fillChar,omitempty"`
	StartX      int32         `protobuf:"varint,15,opt,name=startX,proto3" json:"startX,omitempty"`
	StartY      int32         `protobuf:"varint,16,opt,name=startY,proto3" json:"startY,omitempty"`
	Width       int32         `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	Height      int32         `protobuf:"varint,18,opt,name=Height,proto3" json:"Height,omitempty"`
	RawContents []*PixelSlice `protobuf:"bytes,19,rep,name=rawContents,proto3" json:"rawContents,omitempty"`
	BorderSt    *Style        `protobuf:"bytes,20,opt,name=borderSt,proto3" json:"borderSt,omitempty"`
	FillSt      *Style        `protobuf:"bytes,21,opt,name=fillSt,proto3" json:"fillSt,omitempty"`
}

func (x *DivBox) Reset() {
	*x = DivBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivBox) ProtoMessage() {}

func (x *DivBox) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivBox.ProtoReflect.Descriptor instead.
func (*DivBox) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{3}
}

func (x *DivBox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DivBox) GetBorder() bool {
	if x != nil {
		return x.Border
	}
	return false
}

func (x *DivBox) GetBorderW() int32 {
	if x != nil {
		return x.BorderW
	}
	return 0
}

func (x *DivBox) GetBorderChar() int32 {
	if x != nil {
		return x.BorderChar
	}
	return 0
}

func (x *DivBox) GetFillChar() int32 {
	if x != nil {
		return x.FillChar
	}
	return 0
}

func (x *DivBox) GetStartX() int32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *DivBox) GetStartY() int32 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *DivBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DivBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DivBox) GetRawContents() []*PixelSlice {
	if x != nil {
		return x.RawContents
	}
	return nil
}

func (x *DivBox) GetBorderSt() *Style {
	if x != nil {
		return x.BorderSt
	}
	return nil
}

func (x *DivBox) GetFillSt() *Style {
	if x != nil {
		return x.FillSt
	}
	return nil
}

type TextBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content  string   `protobuf:"bytes,10,opt,name=content,proto3" json:"content,omitempty"`
	Wrap     bool     `protobuf:"varint,11,opt,name=wrap,proto3" json:"wrap,omitempty"`
	Style    *Style   `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	DivNames []string `protobuf:"bytes,15,rep,name=divNames,proto3" json:"divNames,omitempty"`
}

func (x *TextBlob) Reset() {
	*x = TextBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlob) ProtoMessage() {}

func (x *TextBlob) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlob.ProtoReflect.Descriptor instead.
func (*TextBlob) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{4}
}

func (x *TextBlob) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextBlob) GetWrap() bool {
	if x != nil {
		return x.Wrap
	}
	return false
}

func (x *TextBlob) GetStyle() *Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *TextBlob) GetDivNames() []string {
	if x != nil {
		return x.DivNames
	}
	return nil
}

type DivBoxes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxes []*DivBox `protobuf:"bytes,10,rep,name=boxes,proto3" json:"boxes,omitempty"`
}

func (x *DivBoxes) Reset() {
	*x = DivBoxes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivBoxes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivBoxes) ProtoMessage() {}

func (x *DivBoxes) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivBoxes.ProtoReflect.Descriptor instead.
func (*DivBoxes) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{5}
}

func (x *DivBoxes) GetBoxes() []*DivBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type Style struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fg   string `protobuf:"bytes,10,opt,name=fg,proto3" json:"fg,omitempty"`
	Bg   string `protobuf:"bytes,11,opt,name=bg,proto3" json:"bg,omitempty"`
	Attr string `protobuf:"bytes,12,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *Style) Reset() {
	*x = Style{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Style) ProtoMessage() {}

func (x *Style) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Style.ProtoReflect.Descriptor instead.
func (*Style) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{6}
}

func (x *Style) GetFg() string {
	if x != nil {
		return x.Fg
	}
	return ""
}

func (x *Style) GetBg() string {
	if x != nil {
		return x.Bg
	}
	return ""
}

func (x *Style) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type Elements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextBlobs []*TextBlob `protobuf:"bytes,10,rep,name=textBlobs,proto3" json:"textBlobs,omitempty"`
}

func (x *Elements) Reset() {
	*x = Elements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Elements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Elements) ProtoMessage() {}

func (x *Elements) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Elements.ProtoReflect.Descriptor instead.
func (*Elements) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{7}
}

func (x *Elements) GetTextBlobs() []*TextBlob {
	if x != nil {
		return x.TextBlobs
	}
	return nil
}

type FeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DivBoxes *DivBoxes `protobuf:"bytes,10,opt,name=divBoxes,proto3" json:"divBoxes,omitempty"`
	Elements *Elements `protobuf:"bytes,11,opt,name=elements,proto3" json:"elements,omitempty"`
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{8}
}

func (x *FeedResponse) GetDivBoxes() *DivBoxes {
	if x != nil {
		return x.DivBoxes
	}
	return nil
}

func (x *FeedResponse) GetElements() *Elements {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_uggly_proto protoreflect.FileDescriptor

var file_uggly_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75,
	0x67, 0x67, 0x6c, 0x79, 0x22, 0x29, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x32, 0x0a, 0x0a, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x52, 0x06, 0x70, 0x69, 0x78,
	0x65, 0x6c, 0x73, 0x22, 0x4f, 0x0a, 0x05, 0x50, 0x69, 0x78, 0x65, 0x6c, 0x12, 0x0c, 0x0a, 0x01,
	0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x63, 0x12, 0x1c, 0x0a, 0x02, 0x73, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x52, 0x02, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x42, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x42, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0xed, 0x02, 0x0a, 0x06, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x57, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x57, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x68, 0x61, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x6c, 0x43, 0x68, 0x61,
	0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6c, 0x43, 0x68, 0x61,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x59, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x59, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x33, 0x0a, 0x0b, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x13,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x50, 0x69, 0x78,
	0x65, 0x6c, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x0b, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53,
	0x74, 0x79, 0x6c, 0x65, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x12, 0x24,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x6c, 0x53, 0x74, 0x22, 0x78, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x62,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x72,
	0x61, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x77, 0x72, 0x61, 0x70, 0x12, 0x22,
	0x0a, 0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x05, 0x73, 0x74, 0x79,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x2f,
	0x0a, 0x08, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6f,
	0x78, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x67, 0x67, 0x6c,
	0x79, 0x2e, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x52, 0x05, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x22,
	0x3b, 0x0a, 0x05, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x67, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x66, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x67, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x62, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x22, 0x39, 0x0a, 0x08,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74,
	0x42, 0x6c, 0x6f, 0x62, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x09, 0x74, 0x65,
	0x78, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x73, 0x22, 0x68, 0x0a, 0x0c, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x64, 0x69, 0x76, 0x42, 0x6f,
	0x78, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x67, 0x67, 0x6c,
	0x79, 0x2e, 0x44, 0x69, 0x76, 0x42, 0x6f, 0x78, 0x65, 0x73, 0x52, 0x08, 0x64, 0x69, 0x76, 0x42,
	0x6f, 0x78, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x3c, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x46, 0x65, 0x65, 0x64, 0x12, 0x12, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x46, 0x65, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65,
	0x6e, 0x64, 0x69, 0x63, 0x6f, 0x74, 0x74, 0x2f, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uggly_proto_rawDescOnce sync.Once
	file_uggly_proto_rawDescData = file_uggly_proto_rawDesc
)

func file_uggly_proto_rawDescGZIP() []byte {
	file_uggly_proto_rawDescOnce.Do(func() {
		file_uggly_proto_rawDescData = protoimpl.X.CompressGZIP(file_uggly_proto_rawDescData)
	})
	return file_uggly_proto_rawDescData
}

var file_uggly_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_uggly_proto_goTypes = []interface{}{
	(*FeedRequest)(nil),  // 0: uggly.FeedRequest
	(*PixelSlice)(nil),   // 1: uggly.PixelSlice
	(*Pixel)(nil),        // 2: uggly.Pixel
	(*DivBox)(nil),       // 3: uggly.DivBox
	(*TextBlob)(nil),     // 4: uggly.TextBlob
	(*DivBoxes)(nil),     // 5: uggly.DivBoxes
	(*Style)(nil),        // 6: uggly.Style
	(*Elements)(nil),     // 7: uggly.Elements
	(*FeedResponse)(nil), // 8: uggly.FeedResponse
}
var file_uggly_proto_depIdxs = []int32{
	2,  // 0: uggly.PixelSlice.pixels:type_name -> uggly.Pixel
	6,  // 1: uggly.Pixel.st:type_name -> uggly.Style
	1,  // 2: uggly.DivBox.rawContents:type_name -> uggly.PixelSlice
	6,  // 3: uggly.DivBox.borderSt:type_name -> uggly.Style
	6,  // 4: uggly.DivBox.fillSt:type_name -> uggly.Style
	6,  // 5: uggly.TextBlob.style:type_name -> uggly.Style
	3,  // 6: uggly.DivBoxes.boxes:type_name -> uggly.DivBox
	4,  // 7: uggly.Elements.textBlobs:type_name -> uggly.TextBlob
	5,  // 8: uggly.FeedResponse.divBoxes:type_name -> uggly.DivBoxes
	7,  // 9: uggly.FeedResponse.elements:type_name -> uggly.Elements
	0,  // 10: uggly.Feed.GetFeed:input_type -> uggly.FeedRequest
	8,  // 11: uggly.Feed.GetFeed:output_type -> uggly.FeedResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_uggly_proto_init() }
func file_uggly_proto_init() {
	if File_uggly_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uggly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PixelSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pixel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivBoxes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Style); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Elements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uggly_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uggly_proto_goTypes,
		DependencyIndexes: file_uggly_proto_depIdxs,
		MessageInfos:      file_uggly_proto_msgTypes,
	}.Build()
	File_uggly_proto = out.File
	file_uggly_proto_rawDesc = nil
	file_uggly_proto_goTypes = nil
	file_uggly_proto_depIdxs = nil
}
