// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: uggly.proto

package uggly

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Screen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Height   int32  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Width    int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Contents string `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *Screen) Reset() {
	*x = Screen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{0}
}

func (x *Screen) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Screen) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Screen) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Screen) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

type Screens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set     *ScreenSet `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Screens []*Screen  `protobuf:"bytes,2,rep,name=screens,proto3" json:"screens,omitempty"`
}

func (x *Screens) Reset() {
	*x = Screens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screens) ProtoMessage() {}

func (x *Screens) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screens.ProtoReflect.Descriptor instead.
func (*Screens) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{1}
}

func (x *Screens) GetSet() *ScreenSet {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *Screens) GetScreens() []*Screen {
	if x != nil {
		return x.Screens
	}
	return nil
}

type ScreenSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ScreenSet) Reset() {
	*x = ScreenSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uggly_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreenSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenSet) ProtoMessage() {}

func (x *ScreenSet) ProtoReflect() protoreflect.Message {
	mi := &file_uggly_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenSet.ProtoReflect.Descriptor instead.
func (*ScreenSet) Descriptor() ([]byte, []int) {
	return file_uggly_proto_rawDescGZIP(), []int{2}
}

func (x *ScreenSet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ScreenSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_uggly_proto protoreflect.FileDescriptor

var file_uggly_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75,
	0x67, 0x67, 0x6c, 0x79, 0x22, 0x62, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x56, 0x0a, 0x07, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53,
	0x65, 0x74, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x75, 0x67, 0x67, 0x6c, 0x79,
	0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x07, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73,
	0x22, 0x2f, 0x0a, 0x09, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x32, 0x3d, 0x0a, 0x08, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x31, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x12, 0x10, 0x2e, 0x75, 0x67,
	0x67, 0x6c, 0x79, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x53, 0x65, 0x74, 0x1a, 0x0d, 0x2e,
	0x75, 0x67, 0x67, 0x6c, 0x79, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x65, 0x6e, 0x64, 0x69, 0x63, 0x6f, 0x74, 0x74, 0x2f, 0x75, 0x67, 0x67, 0x6c, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uggly_proto_rawDescOnce sync.Once
	file_uggly_proto_rawDescData = file_uggly_proto_rawDesc
)

func file_uggly_proto_rawDescGZIP() []byte {
	file_uggly_proto_rawDescOnce.Do(func() {
		file_uggly_proto_rawDescData = protoimpl.X.CompressGZIP(file_uggly_proto_rawDescData)
	})
	return file_uggly_proto_rawDescData
}

var file_uggly_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_uggly_proto_goTypes = []interface{}{
	(*Screen)(nil),    // 0: uggly.Screen
	(*Screens)(nil),   // 1: uggly.Screens
	(*ScreenSet)(nil), // 2: uggly.ScreenSet
}
var file_uggly_proto_depIdxs = []int32{
	2, // 0: uggly.Screens.set:type_name -> uggly.ScreenSet
	0, // 1: uggly.Screens.screens:type_name -> uggly.Screen
	2, // 2: uggly.Screener.GetScreens:input_type -> uggly.ScreenSet
	0, // 3: uggly.Screener.GetScreens:output_type -> uggly.Screen
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_uggly_proto_init() }
func file_uggly_proto_init() {
	if File_uggly_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uggly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uggly_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreenSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uggly_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uggly_proto_goTypes,
		DependencyIndexes: file_uggly_proto_depIdxs,
		MessageInfos:      file_uggly_proto_msgTypes,
	}.Build()
	File_uggly_proto = out.File
	file_uggly_proto_rawDesc = nil
	file_uggly_proto_goTypes = nil
	file_uggly_proto_depIdxs = nil
}
